FROM {{ singleuser_docker_base_image }}
ARG JUPYTERHUB_VERSION=0.8.1

RUN pip install rise==5.2.0
RUN jupyter nbextension install rise --py --sys-prefix
RUN jupyter nbextension enable rise --py --sys-prefix
